name: loon
description: Loon is a reactive collection data store for Dart & Flutter.
version: 4.0.1
homepage: https://github.com/danReynolds/loon

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  uuid: ^4.3.3
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  path: ^1.8.3
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  